stations:
  - id: "900120013"
    name: "Tram Holteistrasse"
    walking_minutes: 5
  - id: "900120009"
    name: "U Samariterstrasse"
    walking_minutes: 10
  - id: "900120003"
    name: "S Ostkreuz"
    walking_minutes: 10
    lines: ["S41", "S42"]

rotation:
  interval_seconds: 5

display:
  width: 1024
  height: 256
  #width: 256
  #height: 64
  fullscreen: false
  fps: 60
  show_items: 4
  background_color: [0, 0, 0]
  text_color: [255, 170, 0]
  show_remarks: false

refresh:
  interval_seconds: 30
  departure_count: 50

fonts:
  font_header: "JetBrainsMono-Bold.ttf"
  font_main: "JetBrainsMono-Medium.ttf"
  font_remark: "JetBrainsMono-Regular.ttf"

filters:
  suburban: true
  subway: true
  tram: true
  bus: true
  express: true
  regional: true
