stations:
  - id: "900120013"
    name: "Tram Holteistrasse"
    walking_minutes: 5
  - id: "900120009"
    name: "U Samariterstrasse"
    walking_minutes: 10
  - id: "900120003"
    name: "S Ostkreuz"
    walking_minutes: 10
    lines: ["S41", "S42"]

display:
  mode: ssd1322
  width: 256
  height: 64
  fps: 10
  show_remarks: false
  background_color: [0, 0, 0]
  text_color: [255, 170, 0]

fonts:
  font_header: "JetBrainsMono-Bold.ttf"
  font_main: "JetBrainsMono-Medium.ttf"
  font_remark: "JetBrainsMono-Regular.ttf"

rotation:
  interval_seconds: 10

refresh:
  interval_seconds: 30
  departure_count: 10

filters:
  suburban: true
  subway: true
  tram: true
  bus: true
  express: true
  regional: true
