stations:
  - id: "900120013"
    name: "Tram Holteistrasse"
    walking_minutes: 5
  - id: "900120009"
    name: "U Samariterstrasse"
    walking_minutes: 10
  - id: "900120003"
    name: "S Ostkreuz"
    walking_minutes: 10

rotation:
  interval_seconds: 10

display:
  width: 1024
  height: 256
  fullscreen: false
  fps: 30
  background_color: [0, 0, 0]
  text_color: [255, 170, 0]

refresh:
  interval_seconds: 30
  departure_count: 50

filters:
  suburban: true
  subway: true
  tram: true
  bus: false
  ferry: false
  express: true
  regional: true
